name: Update File List

on:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.md'
  workflow_dispatch: # 允许手动触发

jobs:
  update-file-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate file list
      run: node project-files/generate-file-list.js
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add project-files/file-list.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update file list"
        git push 